# Generated by Django 4.1 on 2022-09-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_pin_code_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='New', max_length=15),
        ),
    ]
